var sneakersArr=[
    {
       brend: 'Nike',
       description: 'Кроссовки WMNS NIKE SUPERREP GROOVE',
       background: 'image/sneaker/Rectangle_28.png',
       newSneker: true,
       hit: false,
       discount : 0,
       heart: false,
       price: 274,   
       idProdukt: 0,        
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки WMNS NIKE AIR MAX 2X ' , 
        background: 'image/sneaker/Rectangle_28-1.png' , 
        newSneker: false , 
        hit: false,
        discount: 0,
        heart: false,
        price: 294,
        idProdukt: 1,  
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE AIR MAX ZM950 ' , 
        background: 'image/sneaker/Rectangle_28-2.png' , 
        newSneker:false, 
        hit: true ,
        discount: 0,
        heart: false,
        price: 458,
        idProdukt: 2,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W AIR MAX 270 ' , 
        background: 'image/sneaker/Rectangle_28-3.png ' , 
        newSneker: false, 
        hit:false ,
        discount: 31 ,
        heart: false,
        price: 390,
        idProdukt: 3,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE REACT ART3MIS' , 
        background: ' image/sneaker/Rectangle_28-4.png' , 
        newSneker:true , 
        hit: false,
        discount:0 ,
        heart: false,
        price:274 ,
        idProdukt: 4,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W AF1 PIXEL ' , 
        background: ' image/sneaker/Rectangle_28-5.png' , 
        newSneker:false , 
        hit:false ,
        discount: 31,
        heart: false,
        price:228 ,
        idProdukt: 5,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки WMNS NIKE SUPERREP GROOVE ' , 
        background: 'image/sneaker/Rectangle_28-6.png' , 
        newSneker:false , 
        hit: true ,
        discount:0 ,
        heart: false,
        price:246,
        idProdukt: 6,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки WMNS NIKE RYZ 365 ' , 
        background: 'image/sneaker/Rectangle_28-7.png' , 
        newSneker:false , 
        hit:false ,
        discount: 0,
        heart: false,
        price: 274,
        idProdukt: 7,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки ZOOM 2K WOMEN S SHOE ' , 
        background: 'image/sneaker/Rectangle_28-8.png' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price: 249,
        idProdukt: 8,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки W AF1 SHADOW ' , 
        background: ' image/sneaker/Rectangle_28-9.png' , 
        newSneker:false , 
        hit:false ,
        discount: 0,
        heart: false,
        price:299 ,
        idProdukt: 9,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE AIR MAX ZM950 ' , 
        background: 'image/sneaker/Rectangle_28-10.png' , 
        newSneker: false, 
        hit:false ,
        discount:25 ,
        heart: false,
        price: 458,
        idProdukt: 10,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки M2K TEKNO WOMENS SHOE ' , 
        background: 'image/sneaker/Rectangle_28-11.png' , 
        newSneker: false, 
        hit:false ,
        discount:0 ,
        heart: false,
        price:284 ,
        idProdukt: 11,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки ZOOM 2K WOMENS SHOE ' , 
        background: 'image/sneaker/Rectangle_28-12.png' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price:268 ,
        idProdukt: 12,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки AIR MONARCH IV ' , 
        background: ' image/sneaker/Rectangle_28-13.png' , 
        newSneker:false , 
        hit:false,
        discount:0 ,
        heart: false,
        price:164 ,
        idProdukt: 13,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W AIR MAX EXOSENSE ' , 
        background: ' image/sneaker/Rectangle_28-14.png' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price: 283,
        idProdukt: 14,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE REACT ELEMENT 55 ' , 
        background: 'image/sneaker/Rectangle_28-15.png' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 246 ,
        idProdukt: 15,
    }
    ]
