var sneakersArr=[
    {
       brend: 'Nike',
       description: 'Кроссовки WMNS NIKE SUPERREP GROOVE',
       background: 'image/sneaker/Rectangle_28.png',
       newSneker: true,
       hit: false,
       discount : 0,
       heart: false,
       price: 274,   
       idProdukt: 0,  
       gender: true,      
    },
    {
        brend: 'Nike',
        description: 'Кроссовки WMNS NIKE AIR MAX 2X ' , 
        background: 'image/sneaker/Rectangle_28-1.png' , 
        newSneker: false , 
        hit: false,
        discount: 0,
        heart: false,
        price: 294,
        idProdukt: 1, 
        gender: false,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки W NIKE AIR MAX ZM950 ' , 
        background: 'image/sneaker/Rectangle_28-2.png' , 
        newSneker:false, 
        hit: true ,
        discount: 0,
        heart: false,
        price: 458,
        idProdukt: 2,
        gender: true,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки W AIR MAX 270 ' , 
        background: 'image/sneaker/Rectangle_28-3.png ' , 
        newSneker: false, 
        hit:false ,
        discount: 31 ,
        heart: false,
        price: 390,
        idProdukt: 3,
        gender: false,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки W NIKE REACT ART3MIS' , 
        background: ' image/sneaker/Rectangle_28-4.png' , 
        newSneker:true , 
        hit: false,
        discount:0 ,
        heart: false,
        price:274 ,
        idProdukt: 4,
        gender: false,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки W AF1 PIXEL ' , 
        background: ' image/sneaker/Rectangle_28-5.png' , 
        newSneker:false , 
        hit:false ,
        discount: 31,
        heart: false,
        price:228 ,
        idProdukt: 5,
        gender: false,
    },
    {
        brend: 'Nike',
        description: ' Кроссовки WMNS NIKE SUPERREP GROOVE ' , 
        background: 'image/sneaker/Rectangle_28-6.png' , 
        newSneker:false , 
        hit: true ,
        discount:0 ,
        heart: false,
        price:246,
        idProdukt: 6,
        gender: false,
    },
    {
        brend: 'Nike',
        description: ' Кроссовки WMNS NIKE RYZ 365 ' , 
        background: 'image/sneaker/Rectangle_28-7.png' , 
        newSneker:false , 
        hit:false ,
        discount: 0,
        heart: false,
        price: 274,
        idProdukt: 7,
        gender: false,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки ZOOM 2K WOMEN S SHOE ' , 
        background: 'image/sneaker/Rectangle_28-8.png' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price: 249,
        idProdukt: 8,
        gender: false,
    },
    {
        brend: 'Nike',
        description: ' Кроссовки W AF1 SHADOW ' , 
        background: ' image/sneaker/Rectangle_28-9.png' , 
        newSneker:false , 
        hit:false ,
        discount: 0,
        heart: false,
        price:299 ,
        idProdukt: 9,
        gender: false,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки W NIKE AIR MAX ZM950 ' , 
        background: 'image/sneaker/Rectangle_28-10.png' , 
        newSneker: false, 
        hit:false ,
        discount:25 ,
        heart: false,
        price: 458,
        idProdukt: 10,
        gender: true,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки M2K TEKNO WOMENS SHOE ' , 
        background: 'image/sneaker/Rectangle_28-11.png' , 
        newSneker: false, 
        hit:false ,
        discount:0 ,
        heart: false,
        price:284 ,
        idProdukt: 11,
        gender: true,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки ZOOM 2K WOMENS SHOE ' , 
        background: 'image/sneaker/Rectangle_28-12.png' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price:268 ,
        idProdukt: 12,
        gender: false,
    },
    {
        brend: 'Nike',
        description: ' Кроссовки AIR MONARCH IV ' , 
        background: ' image/sneaker/Rectangle_28-13.png' , 
        newSneker:false , 
        hit:false,
        discount:0 ,
        heart: false,
        price:164 ,
        idProdukt: 13,
        gender: true,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки W AIR MAX EXOSENSE ' , 
        background: ' image/sneaker/Rectangle_28-14.png' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price: 283,
        idProdukt: 14,
        gender: false,
    },
    {
        brend: 'Nike',
        description: 'Кроссовки W NIKE REACT ELEMENT 55 ' , 
        background: 'image/sneaker/Rectangle_28-15.png' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 246 ,
        idProdukt: 15,
        gender: false,
    },
    {
        brend: 'Adidas',
        description: 'Кроссовки для бега Ventice Climacool' , 
        background: 'image/sneaker/adidas/1.png' , 
        newSneker:false , 
        hit: false,
        discount:10 ,
        heart: false,
        price: 388 ,
        idProdukt: 16,
        gender: true,
    },
    {
        brend: 'Adidas',
        description: 'Кроссовки Superstar W NIKE REACT ELEMENT 55 ' , 
        background: 'image/sneaker/adidas/2.png' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 440 ,
        idProdukt: 17,
        gender: true,
    },
    {
        brend: 'Adidas',
        description: 'Кроссовки для бега Adizero Adios 5' , 
        background: 'image/sneaker/adidas/3.png' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 326 ,
        idProdukt: 18,
        gender: true,
    },
    {
        brend: 'Adidas',
        description: 'Кроссовки Ozelia' , 
        background: 'image/sneaker/adidas/4.png' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 480 ,
        idProdukt: 19,
        gender: false,
    },
    {
        brend: 'Reebok',
        description: 'Кроссовки Club C Revenge' , 
        background: 'image/sneaker/adidas/5.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 440  ,
        idProdukt: 20,
        gender: true,
    },
    {
        brend: 'Reebok',
        description: 'Кроссовки Classic Leather' , 
        background: 'image/sneaker/adidas/6.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 446 ,
        idProdukt: 21,
        gender: true,
    },
    {
        brend: 'Reebok',
        description: 'Кроссовки Club C Double Geo' , 
        background: 'image/sneaker/adidas/7.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 440 ,
        idProdukt: 22,
        gender: false,
    },
    {
        brend: 'Puma',
        description: 'Обувь Suede Classic XXI High Risk' , 
        background: 'image/sneaker/adidas/8.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 335 ,
        idProdukt: 23,
        gender: true,
    },
    {
        brend: 'Puma',
        description: 'Обувь Cruise Rider Silk Road' , 
        background: 'image/sneaker/adidas/9.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 409 ,
        idProdukt: 24,
        gender: false,
    },
    {
        brend: 'Puma',
        description: 'Обувь Kosmo Rider Wns' , 
        background: 'image/sneaker/adidas/10.jpg' , 
        newSneker:true , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 449 ,
        idProdukt: 25,
        gender: false,
    },
    {
        brend: 'Adidas',
        description: 'Кроссовки Superstar' , 
        background: 'image/sneaker/adidas/11.jpg' , 
        newSneker:false , 
        hit: true,
        discount:0 ,
        heart: false,
        price: 336 ,
        idProdukt: 26,
        gender: false,
    },
    {
        brend: 'Adidas',
        description: 'Кроссовки Ozrah' , 
        background: 'image/sneaker/adidas/12.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 550 ,
        idProdukt: 27,
        gender: false,
    },
    {
        brend: 'Reebok',
        description: 'Кроссовки Zig Kinetica 2.5 Plus' , 
        background: 'image/sneaker/adidas/13.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 290 ,
        idProdukt: 28,
        gender: false,
    },
    {
        brend: 'Reebok',
        description: 'Кроссовки Club C Cleated Mid' , 
        background: 'image/sneaker/adidas/14.jpg' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 320 ,
        idProdukt: 29,
        gender: false,
    },
    
    ]
    
