var sneakersArr=[
    {
       brend: 'Nike',
       description: 'Кроссовки WMNS NIKE SUPERREP GROOVE',
       background: 'background:url(image/sneaker/Rectangle_28.png)center center no-repeat,#f3f3f399;',
       newSneker: true,
       hit: false,
       discount : 0,
       heart: false,
       price: 274,           
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки WMNS NIKE AIR MAX 2X ' , 
        background: 'background:url(image/sneaker/Rectangle_28-1.png)center center no-repeat,#f3f3f399;' , 
        newSneker: false , 
        hit: false,
        discount: 0,
        heart: false,
        price: 294,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE AIR MAX ZM950 ' , 
        background: 'background:url(image/sneaker/Rectangle_28-2.png)center center no-repeat,#f3f3f399; ' , 
        newSneker:false, 
        hit: true ,
        discount: 0,
        heart: false,
        price: 458,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W AIR MAX 270 ' , 
        background: 'background:url(image/sneaker/Rectangle_28-3.png)center center no-repeat,#f3f3f399; ' , 
        newSneker: false, 
        hit:false ,
        discount: 31 ,
        heart: false,
        price: 390,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE REACT ART3MIS' , 
        background: ' background:url(image/sneaker/Rectangle_28-4.png)center center no-repeat,#f3f3f399;' , 
        newSneker:true , 
        hit: false,
        discount:0 ,
        heart: false,
        price:274 ,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W AF1 PIXEL ' , 
        background: ' background:url(image/sneaker/Rectangle_28-5.png)center center no-repeat,#f3f3f399;' , 
        newSneker:false , 
        hit:false ,
        discount: 31,
        heart: false,
        price:228 ,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки WMNS NIKE SUPERREP GROOVE ' , 
        background: ' background:url(image/sneaker/Rectangle_28-6.png)center center no-repeat,#f3f3f399;' , 
        newSneker:false , 
        hit: true ,
        discount:0 ,
        heart: false,
        price:246,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки WMNS NIKE RYZ 365 ' , 
        background: ' background:url(image/sneaker/Rectangle_28-7.png)center center no-repeat,#f3f3f399;' , 
        newSneker:false , 
        hit:false ,
        discount: 0,
        heart: false,
        price: 274,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки ZOOM 2K WOMEN S SHOE ' , 
        background: 'background:url(image/sneaker/Rectangle_28-8.png)center center no-repeat,#f3f3f399; ' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price: 249,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки W AF1 SHADOW ' , 
        background: ' background:url(image/sneaker/Rectangle_28-9.png)center center no-repeat,#f3f3f399;' , 
        newSneker:false , 
        hit:false ,
        discount: 0,
        heart: false,
        price:299 ,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE AIR MAX ZM950 ' , 
        background: ' background:url(image/sneaker/Rectangle_28-10.png)center center no-repeat,#f3f3f399;' , 
        newSneker: false, 
        hit:false ,
        discount:25 ,
        heart: false,
        price: 458,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки M2K TEKNO WOMENS SHOE ' , 
        background: 'background:url(image/sneaker/Rectangle_28-11.png)center center no-repeat,#f3f3f399; ' , 
        newSneker: false, 
        hit:false ,
        discount:0 ,
        heart: false,
        price:284 ,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки ZOOM 2K WOMENS SHOE ' , 
        background: 'background:url(image/sneaker/Rectangle_28-12.png)center center no-repeat,#f3f3f399; ' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price:268 ,
    },
    {
        brend: 'Nike ',
        description: ' Кроссовки AIR MONARCH IV ' , 
        background: ' background:url(image/sneaker/Rectangle_28-13.png)center center no-repeat,#f3f3f399;' , 
        newSneker:false , 
        hit:false,
        discount:0 ,
        heart: false,
        price:164 ,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W AIR MAX EXOSENSE ' , 
        background: ' background:url(image/sneaker/Rectangle_28-14.png)center center no-repeat,#f3f3f399;' , 
        newSneker:false , 
        hit:false ,
        discount:0 ,
        heart: false,
        price: 283,
    },
    {
        brend: 'Nike ',
        description: 'Кроссовки W NIKE REACT ELEMENT 55 ' , 
        background: 'background:url(image/sneaker/Rectangle_28-15.png)center center no-repeat,#f3f3f399; ' , 
        newSneker:false , 
        hit: false,
        discount:0 ,
        heart: false,
        price: 246 ,
    }
    ]
